// =============================================================================
//                        Copyright Inusoft Studios
// =============================================================================

#ifndef SHIBA_PLATFORM_SURFACE_H_
#define SHIBA_PLATFORM_SURFACE_H_

#include "handle.hpp"
#include "types.h"

namespace shiba {
struct AllocationCallbacks;

// Enumerates various types of events that can be generated by a surface, such as a window or
// user interface element.
enum class SurfaceEventType : u8 {
    None,
    Close,
    Resize,
    KeyDown,
    KeyUp,
    MouseMove,
    MouseButtonDown,
    MouseButtonUp,
    MouseWheel,
    MouseScroll,
    MouseEnter,
    MouseLeave,
    Focus,
};

struct Extent2D { u32 width, height; };

// Represents an event generated by a surface, such as a window or user interface element.
struct SurfaceEvent {
    u8               _pad[3];
    SurfaceEventType mType;
    union {
        Extent2D                 extent;
        struct { i32 mX, mY; }   mouseMove;
        struct { i32 mKey; }     keyDown;
        struct { i32 mKey; }     keyUp;
        struct { i32 mButton; }  mouseButton;
        struct { i32 mX, mY; }   scroll;
        struct { i32 mX, mY; }   mouseWheel;
        struct { i32 mX, mY; }   mouseEnter;
        struct { i32 mX, mY; }   mouseLeave;
        struct { bool bGained; } mFocus;
    };
};

// Represents the description of a surface for creation or configuration.
struct SurfaceDesc {
    const char* pTitle;
    Extent2D    extent;
    bool        bResizable;
    u8          _pad[7];
};

// The OS surface to draw on, this could be a window on desktop or another surface on console.
using Surface      = Handle<struct SurfaceTag>;
using NativeHandle = void*;     // HWND / ANativeWindow*, back-end specific

Surface      createSurface         (const SurfaceDesc& desc, const AllocationCallbacks* alloc);
void         destroySurface        (Surface surface);
bool         surfacePollEvent      (Surface surface, SurfaceEvent* out);
bool         surfaceShouldClose    (Surface surface);
Extent2D     surfaceGetExtent      (Surface surface);
NativeHandle surfaceGetNativeHandle(Surface surface);
void         surfaceSetTitle       (Surface surface, const char* title);

}  // namespace shiba

#endif  // SHIBA_PLATFORM_SURFACE_H_
